name: flutter_task_systems_ltd
description: A Flutter app for browsing products from FakeStore API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1

  # HTTP Client
  dio: ^5.4.0

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Dependency Injection
  get_it: ^7.6.4

  # Utilities
  equatable: ^2.0.5
  cached_network_image: ^3.3.0
  google_fonts: ^6.3.3
  flutter_native_splash: ^2.4.7
  easy_localization: ^3.0.8
  flutter_screenutil: ^5.9.3
  flutter_rating_bar: ^4.0.1
  connectivity_plus: ^6.0.1
  shimmer: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.14.4

flutter_assets_generator:
  output_dir: core/generated

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/translations/